/**
 * Tests for adr_generator module
 *
 * Tests ADR markdown generation and Slack formatting
 */

import { assertEquals, assertStringIncludes } from "@std/assert";
import {
  formatADRForSlack,
  generateADRMarkdown,
} from "../utils/adr_generator.ts";
import { DecisionRecord, VoteRecord } from "../types/decision_types.ts";
import { DecisionResult } from "../utils/decision_logic.ts";

Deno.test("adr_generator - generateADRMarkdown creates valid markdown for approved decision", () => {
  const decision: DecisionRecord = {
    id: "1234567890.123456",
    name: "Adopt TypeScript",
    proposal:
      "We should adopt TypeScript for all new projects to improve type safety.",
    success_criteria: "simple_majority",
    deadline: "2026-02-15T23:59:59.000Z",
    channel_id: "C123456",
    creator_id: "U123456",
    message_ts: "1234567890.123456",
    status: "approved",
    created_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-05T10:30:00.000Z",
  };

  const votes: VoteRecord[] = [
    {
      id: "d1_u1",
      decision_id: "1234567890.123456",
      user_id: "U123456",
      vote_type: "yes",
      voted_at: "2026-02-01T13:00:00.000Z",
    },
    {
      id: "d1_u2",
      decision_id: "1234567890.123456",
      user_id: "U234567",
      vote_type: "yes",
      voted_at: "2026-02-01T14:00:00.000Z",
    },
    {
      id: "d1_u3",
      decision_id: "1234567890.123456",
      user_id: "U345678",
      vote_type: "no",
      voted_at: "2026-02-01T15:00:00.000Z",
    },
  ];

  const outcome: DecisionResult = {
    passed: true,
    reason: "Simple majority achieved with 66.67% yes votes",
    voteCounts: {
      yes: 2,
      no: 1,
      abstain: 0,
      total: 3,
    },
    percentage: 66.67,
  };

  const userMap = new Map<string, string>([
    ["U123456", "Alice"],
    ["U234567", "Bob"],
    ["U345678", "Charlie"],
  ]);

  const adr = generateADRMarkdown(decision, votes, outcome, userMap);

  // Verify key elements are present
  assertStringIncludes(adr, "# Adopt TypeScript");
  assertStringIncludes(adr, "**Status:** Accepted");
  assertStringIncludes(adr, "**Decision ID:** 1234567890.123456");
  assertStringIncludes(adr, "**Success Criteria:** Simple Majority");
  assertStringIncludes(adr, decision.proposal);
  assertStringIncludes(adr, "**Outcome:** ✅ APPROVED");
  assertStringIncludes(adr, "Simple majority achieved with 66.67% yes votes");
  assertStringIncludes(adr, "- Yes: 2");
  assertStringIncludes(adr, "- No: 1");
  assertStringIncludes(adr, "- Abstain: 0");
  assertStringIncludes(adr, "- Total Votes: 3");
  assertStringIncludes(adr, "✅ Alice: YES");
  assertStringIncludes(adr, "✅ Bob: YES");
  assertStringIncludes(adr, "❌ Charlie: NO");
  assertStringIncludes(
    adr,
    "This ADR was automatically generated by ConsensusBot",
  );
});

Deno.test("adr_generator - generateADRMarkdown creates valid markdown for rejected decision", () => {
  const decision: DecisionRecord = {
    id: "1234567890.123456",
    name: "Switch to MongoDB",
    proposal: "We should switch our database to MongoDB.",
    success_criteria: "super_majority",
    deadline: "2026-02-15T23:59:59.000Z",
    channel_id: "C123456",
    creator_id: "U123456",
    message_ts: "1234567890.123456",
    status: "rejected",
    created_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-05T10:30:00.000Z",
  };

  const votes: VoteRecord[] = [
    {
      id: "d1_u1",
      decision_id: "1234567890.123456",
      user_id: "U123456",
      vote_type: "yes",
      voted_at: "2026-02-01T13:00:00.000Z",
    },
    {
      id: "d1_u2",
      decision_id: "1234567890.123456",
      user_id: "U234567",
      vote_type: "no",
      voted_at: "2026-02-01T14:00:00.000Z",
    },
    {
      id: "d1_u3",
      decision_id: "1234567890.123456",
      user_id: "U345678",
      vote_type: "no",
      voted_at: "2026-02-01T15:00:00.000Z",
    },
  ];

  const outcome: DecisionResult = {
    passed: false,
    reason: "Supermajority not achieved. Need ≥66%, got 33.33%",
    voteCounts: {
      yes: 1,
      no: 2,
      abstain: 0,
      total: 3,
    },
    percentage: 33.33,
    requiredVotersCount: 3,
  };

  const userMap = new Map<string, string>();

  const adr = generateADRMarkdown(decision, votes, outcome, userMap);

  // Verify rejection elements
  assertStringIncludes(adr, "**Status:** Rejected");
  assertStringIncludes(adr, "**Success Criteria:** Super Majority");
  assertStringIncludes(adr, "**Outcome:** ❌ REJECTED");
  assertStringIncludes(adr, "Supermajority not achieved");
  assertStringIncludes(adr, "- Required Voters: 3");
  assertStringIncludes(adr, "N/A - Decision was not approved");
  assertStringIncludes(
    adr,
    "No implementation required as decision was rejected",
  );
});

Deno.test("adr_generator - generateADRMarkdown handles abstain votes", () => {
  const decision: DecisionRecord = {
    id: "1234567890.123456",
    name: "Test Decision",
    proposal: "Test proposal",
    success_criteria: "unanimous",
    deadline: "2026-02-15T23:59:59.000Z",
    channel_id: "C123456",
    creator_id: "U123456",
    message_ts: "1234567890.123456",
    status: "approved",
    created_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-05T10:30:00.000Z",
  };

  const votes: VoteRecord[] = [
    {
      id: "d1_u1",
      decision_id: "1234567890.123456",
      user_id: "U123456",
      vote_type: "yes",
      voted_at: "2026-02-01T13:00:00.000Z",
    },
    {
      id: "d1_u2",
      decision_id: "1234567890.123456",
      user_id: "U234567",
      vote_type: "abstain",
      voted_at: "2026-02-01T14:00:00.000Z",
    },
  ];

  const outcome: DecisionResult = {
    passed: true,
    reason: "Unanimity achieved with 1 yes vote(s) and 1 abstention(s)",
    voteCounts: {
      yes: 1,
      no: 0,
      abstain: 1,
      total: 2,
    },
    percentage: 50.0,
  };

  const userMap = new Map<string, string>([
    ["U123456", "Alice"],
    ["U234567", "Bob"],
  ]);

  const adr = generateADRMarkdown(decision, votes, outcome, userMap);

  // Verify abstain vote is included with correct emoji
  assertStringIncludes(adr, "⚪ Bob: ABSTAIN");
  assertStringIncludes(adr, "- Abstain: 1");
  assertStringIncludes(adr, "**Success Criteria:** Unanimous");
});

Deno.test("adr_generator - formatADRForSlack creates proper Slack blocks", () => {
  const adrMarkdown = `# Test Decision

**Status:** Accepted
**Date:** 2026-02-01

## Context

Test proposal

## Decision

Approved!`;

  const blocks = formatADRForSlack(adrMarkdown);

  // Should have 3 blocks: header, markdown, and context
  assertEquals(blocks.length, 3);

  // First block should be a section with header text
  assertEquals(blocks[0].type, "section");
  assertStringIncludes(
    blocks[0].text?.text ?? "",
    "Architecture Decision Record Generated",
  );

  // Second block should contain the markdown in a code block
  assertEquals(blocks[1].type, "section");
  assertStringIncludes(blocks[1].text?.text ?? "", "```");
  assertStringIncludes(blocks[1].text?.text ?? "", adrMarkdown);

  // Third block should be context with archival instructions
  assertEquals(blocks[2].type, "context");
  const elementText = blocks[2].elements?.[0]?.text;
  const safeText = typeof elementText === "string"
    ? elementText
    : elementText?.text || "";
  assertStringIncludes(
    safeText,
    "To archive this ADR",
  );
});

Deno.test("adr_generator - generateADRMarkdown uses user IDs when names not in map", () => {
  const decision: DecisionRecord = {
    id: "1234567890.123456",
    name: "Test Decision",
    proposal: "Test proposal",
    success_criteria: "simple_majority",
    deadline: "2026-02-15T23:59:59.000Z",
    channel_id: "C123456",
    creator_id: "U123456",
    message_ts: "1234567890.123456",
    status: "approved",
    created_at: "2026-02-01T12:00:00.000Z",
    updated_at: "2026-02-05T10:30:00.000Z",
  };

  const votes: VoteRecord[] = [
    {
      id: "d1_u1",
      decision_id: "1234567890.123456",
      user_id: "U123456",
      vote_type: "yes",
      voted_at: "2026-02-01T13:00:00.000Z",
    },
  ];

  const outcome: DecisionResult = {
    passed: true,
    reason: "Simple majority achieved",
    voteCounts: {
      yes: 1,
      no: 0,
      abstain: 0,
      total: 1,
    },
    percentage: 100.0,
  };

  // Empty user map - should fall back to user IDs
  const userMap = new Map<string, string>();

  const adr = generateADRMarkdown(decision, votes, outcome, userMap);

  // Should use user ID when name not in map
  assertStringIncludes(adr, "✅ U123456: YES");
});
