/**
 * ADR (Architecture Decision Record) Generator for Slack ROSI
 * 
 * Generates ADR markdown from finalized decisions for manual archival
 */

import { DecisionResult } from "./decision_logic.ts";
import { DecisionRecord, VoteRecord } from "../types/decision_types.ts";

// Re-export for backward compatibility
export type Decision = DecisionRecord;
export type { VoteRecord };

/**
 * Generate ADR markdown from a finalized decision
 * 
 * @param decision - Decision object
 * @param votes - Array of vote records
 * @param outcome - Decision outcome result
 * @param userMap - Map of user IDs to display names
 * @returns ADR markdown string
 */
export const generateADRMarkdown = (
  decision: Decision,
  votes: VoteRecord[],
  outcome: DecisionResult,
  userMap: Map<string, string>
): string => {
  const createdDate = new Date(decision.created_at);
  const fileName = `${createdDate.toISOString().split('T')[0]}-${decision.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.md`;
  
  const status = outcome.passed ? 'Accepted' : 'Rejected';
  const criteriaDisplay = decision.success_criteria.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
  
  // Build vote summary
  const voteSummary = votes.map(vote => {
    const userName = userMap.get(vote.user_id) || vote.user_id;
    const voteEmoji = vote.vote_type === 'yes' ? '✅' : vote.vote_type === 'no' ? '❌' : '⚪';
    return `- ${voteEmoji} ${userName}: ${vote.vote_type.toUpperCase()}`;
  }).join('\n');
  
  const adr = `# ${decision.name}

**Status:** ${status}  
**Date:** ${createdDate.toISOString().split('T')[0]}  
**Decision ID:** ${decision.id}  
**Success Criteria:** ${criteriaDisplay}

## Context

${decision.proposal}

## Decision

This decision was put to a vote using the **${criteriaDisplay}** consensus criterion.

### Voting Results

**Outcome:** ${outcome.passed ? '✅ APPROVED' : '❌ REJECTED'}  
**Reason:** ${outcome.reason}

**Vote Breakdown:**
- Yes: ${outcome.voteCounts.yes}
- No: ${outcome.voteCounts.no}
- Abstain: ${outcome.voteCounts.abstain}
- Total Votes: ${outcome.voteCounts.total}
${outcome.requiredVotersCount ? `- Required Voters: ${outcome.requiredVotersCount}` : ''}
- Percentage: ${outcome.percentage.toFixed(2)}%

### Individual Votes

${voteSummary}

## Consequences

### If Accepted

${outcome.passed ? 'This decision has been approved and should be implemented as proposed.' : 'N/A - Decision was not approved.'}

### If Rejected

${!outcome.passed ? 'This decision was rejected. The team may revisit this proposal in the future with modifications or abandon it entirely.' : 'N/A - Decision was approved.'}

## Implementation Notes

${outcome.passed ? 'Teams should proceed with implementing the proposal as described in the Context section.' : 'No implementation required as decision was rejected.'}

## References

- **Decision Created:** ${createdDate.toISOString()}
- **Deadline:** ${decision.deadline}
- **Creator:** <@${decision.creator_id}>
- **Total Participants:** ${votes.length}

---

*This ADR was automatically generated by ConsensusBot*  
*Suggested filename: \`${fileName}\`*
`;

  return adr;
};

/**
 * Format ADR for posting in Slack thread
 * 
 * @param adrMarkdown - ADR markdown string
 * @returns Formatted Slack message blocks
 */
export const formatADRForSlack = (adrMarkdown: string) => {
  return [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "📝 *Architecture Decision Record Generated*\n\nThe decision has been finalized. Below is the ADR markdown that can be copied to your documentation repository:"
      }
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: "```\n" + adrMarkdown + "\n```"
      }
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: "💡 *To archive this ADR:* Copy the markdown above and paste it into your team's documentation repository or wiki."
        }
      ]
    }
  ];
};
